server:
  port: 10010
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api #添加路由前缀
  retryable: true
  routes:
    item-service: /item/** #商品微服务
  ignored-services:
    - upload-service
  add-host-header: true
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效
  ribbon:
    ConnectTimeout: 4000 #连接超时时间（ms）
    ReadTimeout: 2000 #通信超时时间（ms）
    OkToRetryOnAllOperations: true #是否对所有操作重试
    MaxAutoRetriesNextServer: 1 #同一服务不同实例的重试次数
    MaxAutoRetries: 1 #同一实例的重试次数
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              tiemoutInMillisecond: 10000 #熔断超时时长